B2bCode\Bundle\CmsFormBundle\Entity\CmsFormField:
    constraints:
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                fields: [ form, name ]
                message: 'b2bcode.cmsform.validation.cmsformfield.unique.name'
    properties:
        label:
            - NotBlank: ~
        name:
            - NotBlank: ~
            # Slugs are used for simplicity
            - Oro\Bundle\ValidationBundle\Validator\Constraints\UrlSafe: ~
        sortOrder:
            - NotBlank: ~
        type:
            - NotBlank: ~
            - NotNull: ~

B2bCode\Bundle\CmsFormBundle\Entity\CmsForm:
    constraints:
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: uuid
        -   Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: alias
    properties:
        name:
            - NotBlank: ~
        alias:
            - NotBlank: ~
            # Slugs are used for simplicity
            - Oro\Bundle\ValidationBundle\Validator\Constraints\UrlSafe: ~
        redirectUrl:
            - Oro\Bundle\ValidationBundle\Validator\Constraints\Url: ~

B2bCode\Bundle\CmsFormBundle\Entity\CmsFormNotification:
    properties:
        email:
            - Email: ~
